### ISSUE TITLE
Zigbee Firmware value set to "0" after reboot ESP32

### ISSUE THREAD

**Issue by reichelper** [xyzroe/XZG#63]
**Describe the bug**
After reboot the ESP32 with the latest image the Zigbee Firmware Version shows "0"
[See #47](https://github.com/xyzroe/XZG/issues/47)

**Device information**
see Screenshots...

![Screenshot_20240531_235231_Chrome.jpg](https://github.com/xyzroe/XZG/assets/132834852/a822ee0f-c9f2-4179-bd44-9d5fb6881cfe)

**To Reproduce**
1. Reboot ESP32
![Screenshot_20240531_235327_Chrome.jpg](https://github.com/xyzroe/XZG/assets/132834852/5dc0557a-422b-4b4d-9969-b81357771d4a)

2.  Check Zigbee Version
![Screenshot_20240531_235406_Chrome.jpg](https://github.com/xyzroe/XZG/assets/132834852/79ad07bc-5f9e-4142-82d5-945accd4a0df)

3. Zigbee Version is shown as expected 
![Screenshot_20240531_235420_Chrome.jpg](https://github.com/xyzroe/XZG/assets/132834852/8088cf2d-d29b-4a59-a67e-a993b694d4bb)

**Expected behavior**
After Reboot the ESP32 the Zigbee Firmware Version should be show the correct value

**Comment by xyzroe** [comment]
@reichelper could you re-flash Zigbee on the latest XZG firmware, even on the same Zigbee version, and then re-check this issue ?

**Comment by jdm09** [comment]
Same for me.
Since Update to one of the last 4 new ESP32 Firmwares i get the 0 or ? Firmware Version.
I re-flashed several times.
Only in Console i get the correct Version output.
<img width="632" alt="Bildschirmfoto 2024-06-09 um 08 45 53" src="https://github.com/xyzroe/XZG/assets/99863739/271639f4-8a2e-45b6-a827-2f80abcb155b">
<img width="1174" alt="Bildschirmfoto 2024-06-09 um 08 47 30" src="https://github.com/xyzroe/XZG/assets/99863739/acf3736b-16b6-4471-956c-e2e2a6eb0a7e">

**Comment by reichelper** [comment]
@xyzroe 
I flashed the latest ESP32 firmware.
Now after a Reboot of ESP32, the Zigbee Version show "?" instead of "0".

**Comment by xyzroe** [comment]
You need to re-flash Zigbee

**Comment by jdm09** [comment]
I just tried to flash the Zigbee FW and the UZG-01 hangs up at 72,30 % and the red LED is flashing. Whats this?

**Comment by xyzroe** [comment]
So I need to add socket connection and MQTT stoping mechanism. Ok.
